Project repo :-> https://github.com/ProgrammingHero1/B12A06-Green-Earth.git


All API Lnk :-> 

1. Get 🌴All Plants
https://openapi.programming-hero.com/api/plants

2. Get 🌴All categories
https://openapi.programming-hero.com/api/categories

3. Get 🌴plants by categories
https://openapi.programming-hero.com/api/category/${id}
https://openapi.programming-hero.com/api/category/1

4. Get 🌴Plants Detail
https://openapi.programming-hero.com/api/plant/${id}
https://openapi.programming-hero.com/api/plant/1